-- ============================

-- This file was created using Derby's dblook utility.
-- Timestamp: 2012-02-26 19:03:22.934
-- Source database is: bnevins
-- Connection URL is: jdbc:derby://me/bnevins
-- appendLogs: false

-- ----------------------------------------------
-- DDL Statements for tables
-- ----------------------------------------------

CREATE TABLE "APP"."FOO" ("ID" INTEGER);

CREATE TABLE "APP"."USERTABLE" ("USERID" VARCHAR(32) NOT NULL, "PASSWORD" VARCHAR(64) NOT NULL);

CREATE TABLE "APP"."WEIGHT_ITEMS" ("WEIGHT_ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "PERSON" VARCHAR(32) NOT NULL, "WEIGHT" DOUBLE NOT NULL, "DATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE "APP"."SIGNUPTABLE" ("USERID" VARCHAR(32) NOT NULL, "SIGNUPKEY" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1));

CREATE TABLE "APP"."USERINFOTABLE" ("USERID" VARCHAR(32) NOT NULL, "FIRSTNAME" VARCHAR(32), "LASTNAME" VARCHAR(32), "EMAIL" VARCHAR(100));

CREATE TABLE "APP"."GROUPTABLE" ("USERID" VARCHAR(32) NOT NULL, "GROUPID" VARCHAR(32) NOT NULL);

CREATE TABLE "APP"."TODO_ITEMS" ("ITEM_ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "DESCRIPTION" VARCHAR(64) NOT NULL, "ASSIGNEE" VARCHAR(32) NOT NULL, "ASSIGNER" VARCHAR(32) NOT NULL, "OPENED_DATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP, "CLOSED_DATE" TIMESTAMP);

-- ----------------------------------------------
-- DDL Statements for keys
-- ----------------------------------------------

-- primary/unique
ALTER TABLE "APP"."WEIGHT_ITEMS" ADD CONSTRAINT "WEIGHT_ITEM_PK" PRIMARY KEY ("WEIGHT_ID");

ALTER TABLE "APP"."USERTABLE" ADD CONSTRAINT "USER_PK" PRIMARY KEY ("USERID");

ALTER TABLE "APP"."GROUPTABLE" ADD CONSTRAINT "GROUP_FK" PRIMARY KEY ("USERID", "GROUPID");

ALTER TABLE "APP"."TODO_ITEMS" ADD CONSTRAINT "TODO_ITEM_PK" PRIMARY KEY ("ITEM_ID");

ALTER TABLE "APP"."TODO_ITEMS" ADD CONSTRAINT "SQL120226185608640" UNIQUE ("DESCRIPTION");

-- foreign
ALTER TABLE "APP"."SIGNUPTABLE" ADD CONSTRAINT "USERVALID_FK" FOREIGN KEY ("USERID") REFERENCES "APP"."USERTABLE" ("USERID") ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE "APP"."GROUPTABLE" ADD CONSTRAINT "USER_FK" FOREIGN KEY ("USERID") REFERENCES "APP"."USERTABLE" ("USERID") ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE "APP"."USERINFOTABLE" ADD CONSTRAINT "USERINFO_FK" FOREIGN KEY ("USERID") REFERENCES "APP"."USERTABLE" ("USERID") ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE "APP"."TODO_ITEMS" ADD CONSTRAINT "SQL120226185731580" FOREIGN KEY ("ASSIGNEE") REFERENCES "APP"."USERTABLE" ("USERID") ON DELETE NO ACTION ON UPDATE NO ACTION;

