CREATE TABLE TODO_ITEMS (
        ITEM_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY CONSTRAINT TODO_ITEM_PK PRIMARY KEY,
        DESCRIPTION VARCHAR(64) NOT NULL,
        ASSIGNEE VARCHAR(32) NOT NULL CONSTRAINT ASSIGNEE_FK REFERENCES USERTABLE on delete cascade on update restrict,
        ASSIGNER VARCHAR(32) NOT NULL CONSTRAINT ASSIGNER_FK REFERENCES USERTABLE on delete cascade on update restrict,
        OPENED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CLOSED_DATE TIMESTAMP
);

