/*
 * File:           EmployeeHandlerImpl.java
 * Date:           February 13, 2004  12:56 AM
 *
 * @author  bnevins
 * @version generated by NetBeans XML module
 */
package com.elf.xml;

import org.xml.sax.*;

public class EmployeeHandlerImpl implements EmployeeHandler
{
	
	public static final boolean DEBUG = true;
	
	public void start_CARS(final Attributes meta) throws SAXException
	{
		if (DEBUG) System.err.println("start_CARS: " + meta);
	}
	
	public void end_CARS() throws SAXException
	{
		if (DEBUG) System.err.println("end_CARS()");
	}
	
	public void start_CAR(final Attributes meta) throws SAXException
	{
		if (DEBUG) System.err.println("start_CAR: " + meta);
	}
	
	public void end_CAR() throws SAXException
	{
		if (DEBUG) System.err.println("end_CAR()");
	}
	
	public void handle_NAME(final java.lang.String data, final Attributes meta) throws SAXException
	{
		if (DEBUG) System.err.println("handle_NAME: " + data);
	}
	
}

