/*
 * File:           EmployeeHandler.java
 * Date:           February 13, 2004  12:56 AM
 *
 * @author  bnevins
 * @version generated by NetBeans XML module
 */
package com.elf.xml;

import org.xml.sax.*;

public interface EmployeeHandler
{
	
	/**
	 * A container element start event handling method.
	 * @param meta attributes
	 *
	 */
	public void start_CARS(final Attributes meta) throws SAXException;
	
	/**
	 * A container element end event handling method.
	 *
	 */
	public void end_CARS() throws SAXException;
	
	/**
	 * A container element start event handling method.
	 * @param meta attributes
	 *
	 */
	public void start_CAR(final Attributes meta) throws SAXException;
	
	/**
	 * A container element end event handling method.
	 *
	 */
	public void end_CAR() throws SAXException;
	
	/**
	 * A data element event handling method.
	 * @param data value or null
	 * @param meta attributes
	 *
	 */
	public void handle_NAME(final java.lang.String data, final Attributes meta) throws SAXException;
	
}

