CONNECT 'jdbc:derby://localhost:1527/c:/data/db/bnevins;create=true';
CREATE SCHEMA "BNEVINS";
CREATE TABLE "BNEVINS"."USERINFOTABLE" ("USERID" VARCHAR(32) NOT NULL, "FIRSTNAME" VARCHAR(32), "LASTNAME" VARCHAR(32), "EMAIL" VARCHAR(100));
CREATE TABLE "BNEVINS"."TODO_ITEMS" ("ITEM_ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "DESCRIPTION" VARCHAR(64) NOT NULL, "ASSIGNEE" VARCHAR(32) NOT NULL, "ASSIGNER" VARCHAR(32) NOT NULL, "OPENED_DATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP, "CLOSED_DATE" TIMESTAMP);
CREATE TABLE "BNEVINS"."SIGNUPTABLE" ("USERID" VARCHAR(32) NOT NULL, "SIGNUPKEY" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1371918, INCREMENT BY 1));
CREATE TABLE "BNEVINS"."USERTABLE" ("USERID" VARCHAR(32) NOT NULL, "PASSWORD" VARCHAR(32) NOT NULL);
CREATE TABLE "BNEVINS"."GROUPTABLE" ("USERID" VARCHAR(32) NOT NULL, "GROUPID" VARCHAR(32) NOT NULL);
CREATE TABLE "BNEVINS"."WEIGHT_ITEMS" ("WEIGHT_ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "WEIGHT" DOUBLE NOT NULL, "DATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP, "PERSON" VARCHAR(32) NOT NULL);
ALTER TABLE "BNEVINS"."TODO_ITEMS" ADD CONSTRAINT "SQL071007035001450" UNIQUE ("DESCRIPTION");
ALTER TABLE "BNEVINS"."TODO_ITEMS" ADD CONSTRAINT "TODO_ITEM_PK" PRIMARY KEY ("ITEM_ID");
ALTER TABLE "BNEVINS"."GROUPTABLE" ADD CONSTRAINT "GROUP_FK" PRIMARY KEY ("USERID", "GROUPID");
ALTER TABLE "BNEVINS"."USERTABLE" ADD CONSTRAINT "USER_PK" PRIMARY KEY ("USERID");
ALTER TABLE "BNEVINS"."WEIGHT_ITEMS" ADD CONSTRAINT "WEIGHT_ITEM_PK" PRIMARY KEY ("WEIGHT_ID");
ALTER TABLE "BNEVINS"."USERINFOTABLE" ADD CONSTRAINT "USERINFO_FK" FOREIGN KEY ("USERID") REFERENCES "BNEVINS"."USERTABLE" ("USERID") ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE "BNEVINS"."GROUPTABLE" ADD CONSTRAINT "USER_FK" FOREIGN KEY ("USERID") REFERENCES "BNEVINS"."USERTABLE" ("USERID") ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE "BNEVINS"."SIGNUPTABLE" ADD CONSTRAINT "USERVALID_FK" FOREIGN KEY ("USERID") REFERENCES "BNEVINS"."USERTABLE" ("USERID") ON DELETE CASCADE ON UPDATE RESTRICT;



