/*
 * File:           PictureHandler.java
 * Date:           May 7, 2006  1:53 AM
 *
 * @author  bnevins
 * @version generated by NetBeans XML module
 */
/*
 * File:           PictureHandler.java
 * Date:           May 7, 2006  1:16 AM
 *
 * @author  bnevins
 * @version generated by NetBeans XML module
 */
/*
 * File:           PictureHandler.java
 * Date:           May 7, 2006  1:15 AM
 *
 * @author  bnevins
 * @version generated by NetBeans XML module
 */
package com.elf.util.web;

import org.xml.sax.*;
public interface PictureHandler
{

	/**
	 * 
	 * An empty element event handling method.
	 * @param data value or null
	 */
	public void handle_pix(final Attributes meta) throws SAXException;

	/**
	 * 
	 * A container element start event handling method.
	 * @param meta attributes
	 */
	public void start_strip(final Attributes meta) throws SAXException;

	/**
	 * 
	 * A container element end event handling method.
	 */
	public void end_strip() throws SAXException;

	/**
	 * 
	 * A container element start event handling method.
	 * @param meta attributes
	 */
	public void start_project(final Attributes meta) throws SAXException;

	/**
	 * 
	 * A container element end event handling method.
	 */
	public void end_project() throws SAXException;
}
