/*
 * ThumbnailGUI.java
 *
 * Created on June 4, 2006, 12:01 AM
 */

package com.elf.graphics;

/**
 *
 * @author  bnevins
 */
public class ThumbnailGUI extends javax.swing.JFrame
{

    /** Creates new form ThumbnailGUI */
    public ThumbnailGUI(ThumbnailMakerInfo Info)
    {
        info = Info;
        initComponents();
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scalingGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rootDir = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        prefix = new javax.swing.JTextField();
        overwrite = new javax.swing.JCheckBox();
        recursive = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        widthHeight = new javax.swing.JRadioButton();
        maxDim = new javax.swing.JRadioButton();
        bounding = new javax.swing.JRadioButton();
        numberLabel1 = new javax.swing.JLabel();
        numberLabel2 = new javax.swing.JLabel();
        scale = new javax.swing.JRadioButton();
        number1 = new javax.swing.JTextField();
        number2 = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        bounding.setSelected(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "File Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel1.setText("Root Directory:");

        rootDir.setToolTipText("Enter the root directory");

        jLabel2.setText("Thumbnail Prefix:");

        prefix.setText("tn_");
        prefix.setToolTipText("Enter a thumbnail prefix to use");

        overwrite.setText("Overwite");
        overwrite.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        overwrite.setMargin(new java.awt.Insets(0, 0, 0, 0));

        recursive.setText("Recursive");
        recursive.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        recursive.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rootDir, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prefix, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(overwrite)
                        .addGap(67, 67, 67)
                        .addComponent(recursive)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rootDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(prefix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(overwrite)
                    .addComponent(recursive))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Scaling", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel3.setText("Scaling:");

        scalingGroup.add(widthHeight);
        widthHeight.setText("Absolute");
        widthHeight.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        widthHeight.setMargin(new java.awt.Insets(0, 0, 0, 0));
        widthHeight.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                widthHeightItemStateChanged(evt);
            }
        });

        scalingGroup.add(maxDim);
        maxDim.setText("Maximum Dimension");
        maxDim.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        maxDim.setMargin(new java.awt.Insets(0, 0, 0, 0));
        maxDim.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                maxDimItemStateChanged(evt);
            }
        });

        scalingGroup.add(bounding);
        bounding.setText("Bounding Box");
        bounding.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        bounding.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bounding.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boundingItemStateChanged(evt);
            }
        });

        numberLabel1.setLabelFor(number1);
        numberLabel1.setText("width");

        numberLabel2.setLabelFor(number2);
        numberLabel2.setText("height");

        scalingGroup.add(scale);
        scale.setText("Scale");
        scale.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        scale.setMargin(new java.awt.Insets(0, 0, 0, 0));
        scale.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                scaleItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(widthHeight)
                            .addComponent(maxDim)
                            .addComponent(bounding))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(numberLabel1)
                            .addComponent(numberLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(number2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(number1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(scale))
                .addGap(158, 158, 158))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {number1, number2});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberLabel1)
                            .addComponent(number1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberLabel2)
                            .addComponent(number2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(widthHeight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maxDim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bounding)
                        .addGap(4, 4, 4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scale, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bounding, maxDim, scale, widthHeight});

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(ok)
                .addGap(73, 73, 73)
                .addComponent(cancel)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancel, ok});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ok)
                    .addComponent(cancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelActionPerformed
    {//GEN-HEADEREND:event_cancelActionPerformed
        dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_okActionPerformed
    {//GEN-HEADEREND:event_okActionPerformed
        info.setRootDir(rootDir.getText());
        info.setPrefix(prefix.getText());
        info.setOverwrite(overwrite.isSelected());
        info.setRecursive(recursive.isSelected());

        if(widthHeight.isSelected())
        {
            info.setScaleType(ThumbnailMakerInfo.Scales.WIDTH_HEIGHT);
        }
        else if(maxDim.isSelected())
        {
            info.setScaleType(ThumbnailMakerInfo.Scales.MAX_DIM);
        }
        else if(bounding.isSelected())
        {
            info.setScaleType(ThumbnailMakerInfo.Scales.BOUNDING_BOX);
        }
        else if(scale.isSelected())
        {
            info.setScaleType(ThumbnailMakerInfo.Scales.SCALE);
        }

        info.setNumber1(number1.getText());
        info.setNumber2(number2.getText());
        System.out.println(info);
        ThumbnailManager mgr = new ThumbnailManager(info);
        mgr.make();
        dispose();
    }//GEN-LAST:event_okActionPerformed

    private void widthHeightItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_widthHeightItemStateChanged
    {//GEN-HEADEREND:event_widthHeightItemStateChanged
        if(widthHeight.isSelected())
        {
            number2.setVisible(true);
            numberLabel2.setVisible(true);
            numberLabel1.setText("width");
        }
    }//GEN-LAST:event_widthHeightItemStateChanged

    private void boundingItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_boundingItemStateChanged
    {//GEN-HEADEREND:event_boundingItemStateChanged
        if(bounding.isSelected())
        {
            number2.setVisible(true);
            numberLabel2.setVisible(true);
            numberLabel1.setText("width");
        }
    }//GEN-LAST:event_boundingItemStateChanged

    private void scaleItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_scaleItemStateChanged
    {//GEN-HEADEREND:event_scaleItemStateChanged
        if(scale.isSelected())
        {
            number2.setVisible(false);
            numberLabel2.setVisible(false);
            numberLabel1.setText("scale");
        }
    }//GEN-LAST:event_scaleItemStateChanged

    private void maxDimItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_maxDimItemStateChanged
    {//GEN-HEADEREND:event_maxDimItemStateChanged
        if(maxDim.isSelected())
        {
            number2.setVisible(false);
            numberLabel2.setVisible(false);
            numberLabel1.setText("max dimension");
            //number1.set
        }
        else
        {
            number2.setVisible(true);
            numberLabel2.setVisible(true);
            numberLabel1.setText("width");
        }

    }//GEN-LAST:event_maxDimItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        ThumbnailMakerInfo tmi = new ThumbnailMakerInfo();
        ThumbnailGUI gui = new ThumbnailGUI(tmi);
        gui.setVisible(true);
        System.out.println("ROOTDIR: " + tmi.getRootDir());
        /*
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                gui.setVisible(true);
            }
        });
         **/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bounding;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton maxDim;
    private javax.swing.JTextField number1;
    private javax.swing.JTextField number2;
    private javax.swing.JLabel numberLabel1;
    private javax.swing.JLabel numberLabel2;
    private javax.swing.JButton ok;
    private javax.swing.JCheckBox overwrite;
    private javax.swing.JTextField prefix;
    private javax.swing.JCheckBox recursive;
    private javax.swing.JTextField rootDir;
    private javax.swing.JRadioButton scale;
    private javax.swing.ButtonGroup scalingGroup;
    private javax.swing.JRadioButton widthHeight;
    // End of variables declaration//GEN-END:variables
    private ThumbnailMakerInfo info;
}
