connect 'jdbc:derby://localhost:1527/bnevins;user=APP;password=APP';

drop table SIGNUPTABLE;
drop table TODO_ITEMS;
drop table USERINFOTABLE;
drop table GROUPTABLE;
drop table USERTABLE;

create table USERTABLE(
        USERID varchar(32) NOT NULL CONSTRAINT USER_PK PRIMARY KEY ,
        PASSWORD varchar(64) NOT NULL
        );
create table GROUPTABLE(
        USERID varchar(32) NOT NULL, 
        GROUPID varchar(32) NOT NULL,
        CONSTRAINT GROUP_FK PRIMARY KEY(USERID, GROUPID),
        CONSTRAINT USER_FK FOREIGN KEY(USERID) REFERENCES USERTABLE(USERID)
            ON DELETE CASCADE ON UPDATE RESTRICT
    );
create table USERINFOTABLE(
            USERID varchar(32) NOT NULL,
            FIRSTNAME varchar(32), 
            LASTNAME varchar(32), 
            EMAIL varchar(100),
            CONSTRAINT USERINFO_FK FOREIGN KEY(USERID) REFERENCES USERTABLE(USERID)
            ON DELETE CASCADE ON UPDATE RESTRICT
);
create table SIGNUPTABLE (
        USERID          varchar(32) NOT NULL, 
        SIGNUPKEY  int GENERATED ALWAYS AS IDENTITY(START WITH 1),
        CONSTRAINT USERVALID_FK FOREIGN KEY(USERID) REFERENCES USERTABLE(USERID)
            ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE TODO_ITEMS (
	ITEM_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY CONSTRAINT TODO_ITEM_PK PRIMARY KEY, 
	DESCRIPTION VARCHAR(64) NOT NULL,
	ASSIGNEE VARCHAR(32) NOT NULL, 
	ASSIGNER VARCHAR(32) NOT NULL, 
	OPENED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	CLOSED_DATE TIMESTAMP, 
	CONSTRAINT ASSIGNER_FK FOREIGN KEY(ASSIGNER) REFERENCES USERTABLE(USERID), 
	CONSTRAINT ASSIGNEE_FK FOREIGN KEY(ASSIGNEE) REFERENCES USERTABLE(USERID),
	CONSTRAINT NO_DUPES UNIQUE(ASSIGNEE,DESCRIPTION)
);

insert into USERTABLE(USERID,PASSWORD) 
    values ('admin', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918');
insert into GROUPTABLE(USERID,GROUPID) values ('admin', 'USERS');
insert into GROUPTABLE(USERID,GROUPID) values ('admin', 'ADMINISTRATORS');
insert into USERINFOTABLE(USERID,FIRSTNAME,LASTNAME,EMAIL) values ('admin', 'delete or edit me', 'password is admin', '');
insert into SIGNUPTABLE(USERID) values ('admin');
insert into todo_items(description, assigner, assignee) values('desc1', 'admin', 'admin');



