CREATE TABLE TODO_ITEMS (
	ITEM_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY CONSTRAINT TODO_ITEM_PK PRIMARY KEY, 
	DESCRIPTION VARCHAR(64) NOT NULL UNIQUE,
	ASSIGNEE VARCHAR(32) NOT NULL, 
	ASSIGNER VARCHAR(32) NOT NULL, 
	OPENED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	CLOSED_DATE TIMESTAMP, 
	CONSTRAINT ASSIGNER_FK FOREIGN KEY(ASSIGNER) REFERENCES USERTABLE(USERID), 
	CONSTRAINT ASSIGNEE_FK FOREIGN KEY(ASSIGNEE) REFERENCES USERTABLE(USERID) 
);
